#! /bin/bash

apt-get update &&                       \
        apt-get upgrade -y &&           \
        apt-get install -y apt-utils    \
        software-properties-common      \
        build-essential                 \
        sudo                            \
        vim-gtk                         \
        neovim                          \
        zsh                             \
        git                             \
        git-extras                      \
        git-flow                        \
        gcc                             \
        g++                             \
        golang-go                       \
        bison                           \
        flex                            \
        wget                            \
        curl                            \
        libcurl4-openssl-dev            \
        byobu                           \
        tmux                            \
        autotools-dev                   \
        autoconf                        \
        ninja-build                     \
        python3                         \
        python3-dev                     \
        python3-pip                     \
        exuberant-ctags                 \
        ruby                            \
        rake                            \
        nodejs                          \
        ack-grep                        \
        apt-transport-https             \
        cmake                           \
        docker                          \
        libgmp-dev                      \
        libmpc-dev                      \
        libmpfr-dev                     \
        nasm                            \
        texinfo                         \
        openssl                         \
        libssl-dev                      \
        libxml2-dev                     \
        stow                            \
        libpcre3-dev                    \
        clang                           \
        clang-format                    \
        clang-tidy                      \
        lld                             \
        llvm                            \
        llvm-dev                        \
        openssh-server                  \
        emacs                           \
        man                             \
        keychain                        \
        locales                         \
        locales-all                     \
        locate                          \
        fd-find                         \
        ripgrep                         \
        ack-grep                        \
        apt-transport-https             \
        autoconf                        \
        autoconf2.13                    \
        autotools-dev                   \
        bison                           \
        build-essential                 \
        byobu                           \
        ccache                          \
        clang                           \
        clang-format                    \
        clang-tidy                      \
        cmake                           \
        curl                            \
        docker                          \
        emacs                           \
        exuberant-ctags                 \
        fd-find                         \
        flex                            \
        g++                             \
        gcc                             \
        git                             \
        git-extras                      \
        git-flow                        \
        golang-go                       \
        gperf                           \
        keychain                        \
        libbz2-dev                      \
        libcurl4-openssl-dev            \
        libdbus-1-dev                   \
        libegl1-mesa-dev                \
        libfreetype6-dev                \
        libgl1-mesa-dri                 \
        libgles2-mesa-dev               \
        libglib2.0-dev                  \
        libglu1-mesa-dev                \
        libgmp-dev                      \
        libgstreamer-plugins-bad1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer1.0-dev             \
        libharfbuzz-dev                 \
        liblzma-dev                     \
        libmpc-dev                      \
        libmpfr-dev                     \
        libosmesa6-dev                  \
        libpcre3-dev                    \
        libssl-dev                      \
        libunwind-dev                   \
        libx11-dev                      \
        libxml2-dev                     \
        libxmu-dev                      \
        libxmu6                         \
        lld                             \
        llvm                            \
        llvm-dev                        \
        locales                         \
        locales-all                     \
        locate                          \
        man                             \
        nasm                            \
        neovim                          \
        ninja-build                     \
        nodejs                          \
        openssh-server                  \
        openssl                         \
        python                          \
        python-dev                      \
        python-pip                      \
        python-virtualenv               \
        python3                         \
        python3-dev                     \
        python3-pip                     \
        rake                            \
        ripgrep                         \
        ruby                            \
        software-properties-common      \
        stow                            \
        sudo                            \
        texinfo                         \
        tmux                            \
        vim-gtk                         \
        virtualenv                      \
        wget                            \
        xorg-dev                        \
        zsh                             \
        